// Indian states/UTs mapped to their district headquarters and other major
// towns, for the business creation/edit forms' state->city dependent
// dropdowns. Covers every district so any town a pharma business is based
// in should be listed, without trying to enumerate every village.
export const INDIA_STATES_AND_CITIES: Record<string, string[]> = {
  "Andhra Pradesh": [
    "Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Kurnool", "Kadapa", "Anantapur", "Chittoor",
    "Tirupati", "Kakinada", "Rajahmundry", "Eluru", "Ongole", "Srikakulam", "Vizianagaram", "Machilipatnam",
    "Amaravati", "Chilakaluripet", "Narasaraopet", "Tenali", "Proddatur", "Nandyal", "Adoni", "Madanapalle",
    "Hindupur", "Bapatla", "Guntakal", "Tadepalligudem", "Tuni", "Palasa",
  ],
  "Arunachal Pradesh": [
    "Itanagar", "Naharlagun", "Pasighat", "Tawang", "Ziro", "Bomdila", "Aalo", "Changlang",
    "Tezu", "Khonsa", "Yingkiong", "Daporijo", "Roing", "Seppa", "Anini", "Along",
  ],
  Assam: [
    "Guwahati", "Silchar", "Dibrugarh", "Jorhat", "Nagaon", "Tinsukia", "Tezpur", "Karimganj",
    "Sivasagar", "Goalpara", "Barpeta", "Dhubri", "North Lakhimpur", "Diphu", "Golaghat", "Bongaigaon",
    "Hailakandi", "Kokrajhar", "Nalbari", "Morigaon", "Mangaldoi", "Haflong", "Baksa", "Chirang",
    "Dhemaji", "Majuli", "Hojai", "Charaideo", "Biswanath", "South Salmara",
  ],
  Bihar: [
    "Patna", "Gaya", "Bhagalpur", "Muzaffarpur", "Darbhanga", "Purnia", "Arrah", "Bihar Sharif",
    "Begusarai", "Katihar", "Munger", "Chhapra", "Bettiah", "Motihari", "Saharsa", "Sitamarhi",
    "Siwan", "Nawada", "Buxar", "Jehanabad", "Aurangabad", "Sasaram", "Samastipur", "Madhubani",
    "Khagaria", "Kishanganj", "Araria", "Supaul", "Banka", "Jamui", "Lakhisarai", "Sheikhpura",
    "Gopalganj", "Hajipur", "Madhepura", "Jamalpur", "Bagaha", "Dehri",
  ],
  Chhattisgarh: [
    "Raipur", "Bhilai", "Bilaspur", "Korba", "Durg", "Rajnandgaon", "Jagdalpur", "Ambikapur",
    "Raigarh", "Dhamtari", "Mahasamund", "Kanker", "Kawardha", "Janjgir", "Kondagaon", "Dantewada",
    "Balod", "Baloda Bazar", "Bemetara", "Gariaband", "Sukma", "Bijapur", "Narayanpur", "Mungeli",
    "Surajpur", "Balrampur", "Korea", "Jashpur", "Manendragarh", "Sarangarh",
  ],
  Goa: ["Panaji", "Margao", "Vasco da Gama", "Mapusa", "Ponda", "Bicholim", "Curchorem", "Cuncolim", "Canacona", "Sanguem", "Pernem", "Quepem", "Valpoi"],
  Gujarat: [
    "Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar", "Jamnagar", "Junagadh", "Gandhinagar",
    "Anand", "Nadiad", "Mehsana", "Morbi", "Bharuch", "Navsari", "Valsad", "Vapi", "Porbandar",
    "Surendranagar", "Godhra", "Patan", "Palanpur", "Himatnagar", "Amreli", "Botad", "Gandhidham",
    "Bhuj", "Veraval", "Dahod", "Khambhat", "Vyara", "Modasa", "Rajpipla", "Chhota Udaipur",
    "Dwarka", "Ankleshwar", "Jetpur", "Deesa",
  ],
  Haryana: [
    "Faridabad", "Gurugram", "Panipat", "Ambala", "Hisar", "Rohtak", "Karnal", "Sonipat",
    "Yamunanagar", "Panchkula", "Bhiwani", "Sirsa", "Jind", "Kaithal", "Kurukshetra", "Rewari",
    "Palwal", "Jhajjar", "Fatehabad", "Mahendragarh", "Nuh", "Charkhi Dadri",
  ],
  "Himachal Pradesh": [
    "Shimla", "Solan", "Dharamshala", "Mandi", "Kullu", "Una", "Bilaspur", "Hamirpur",
    "Chamba", "Nahan", "Kangra", "Reckong Peo", "Kaza", "Kasauli", "Manali", "Nurpur",
  ],
  Jharkhand: [
    "Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Deoghar", "Hazaribagh", "Giridih", "Ramgarh",
    "Dumka", "Chaibasa", "Chatra", "Gumla", "Koderma", "Latehar", "Lohardaga", "Pakur",
    "Daltonganj", "Sahibganj", "Simdega", "Godda", "Jamtara", "Khunti", "Seraikela", "Garhwa",
    "East Singhbhum", "West Singhbhum",
  ],
  Karnataka: [
    "Bengaluru", "Mysuru", "Hubballi", "Mangaluru", "Belagavi", "Davanagere", "Ballari", "Shivamogga",
    "Tumakuru", "Kalaburagi", "Bidar", "Vijayapura", "Raichur", "Hassan", "Mandya", "Chitradurga",
    "Kolar", "Udupi", "Chikkamagaluru", "Madikeri", "Bagalkot", "Gadag", "Haveri", "Koppal",
    "Yadgir", "Chamarajanagar", "Ramanagara", "Chikkaballapur", "Dharwad", "Vijayanagara",
  ],
  Kerala: [
    "Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur", "Kollam", "Palakkad", "Kannur", "Alappuzha",
    "Kottayam", "Malappuram", "Pathanamthitta", "Idukki", "Ernakulam", "Wayanad", "Kasaragod", "Muvattupuzha",
    "Thodupuzha", "Kayamkulam", "Kanhangad", "Payyanur",
  ],
  "Madhya Pradesh": [
    "Indore", "Bhopal", "Jabalpur", "Gwalior", "Ujjain", "Sagar", "Dewas", "Satna",
    "Ratlam", "Rewa", "Katni", "Singrauli", "Burhanpur", "Khandwa", "Khargone", "Chhindwara",
    "Guna", "Shivpuri", "Vidisha", "Sehore", "Hoshangabad", "Betul", "Damoh", "Mandsaur",
    "Neemuch", "Shajapur", "Sidhi", "Balaghat", "Chhatarpur", "Panna", "Tikamgarh", "Datia",
    "Morena", "Bhind", "Ashoknagar", "Shahdol", "Umaria", "Dindori", "Anuppur", "Jhabua",
    "Alirajpur", "Barwani", "Harda", "Raisen", "Rajgarh", "Seoni", "Mandla", "Narsinghpur",
    "Agar Malwa", "Niwari",
  ],
  Maharashtra: [
    "Mumbai", "Pune", "Nagpur", "Nashik", "Chhatrapati Sambhajinagar", "Solapur", "Kolhapur", "Amravati",
    "Thane", "Navi Mumbai", "Vasai-Virar", "Nanded", "Sangli", "Akola", "Latur", "Dhule",
    "Ahmednagar", "Chandrapur", "Jalgaon", "Bhiwandi", "Malegaon", "Ichalkaranji", "Parbhani", "Panvel",
    "Satara", "Beed", "Yavatmal", "Osmanabad", "Wardha", "Gondia", "Buldhana", "Washim",
    "Hingoli", "Jalna", "Ratnagiri", "Sindhudurg", "Raigad", "Palghar", "Nandurbar", "Bhandara",
    "Gadchiroli", "Pimpri-Chinchwad", "Dhule",
  ],
  Manipur: ["Imphal", "Thoubal", "Bishnupur", "Churachandpur", "Senapati", "Ukhrul", "Tamenglong", "Chandel", "Jiribam", "Kangpokpi", "Kakching", "Noney", "Pherzawl", "Tengnoupal", "Kamjong"],
  Meghalaya: ["Shillong", "Tura", "Jowai", "Nongstoin", "Baghmara", "Williamnagar", "Nongpoh", "Mairang", "Resubelpara", "Ampati", "Khliehriat", "Mawkyrwat"],
  Mizoram: ["Aizawl", "Lunglei", "Champhai", "Serchhip", "Kolasib", "Lawngtlai", "Mamit", "Saiha", "Khawzawl", "Hnahthial", "Saitual"],
  Nagaland: ["Kohima", "Dimapur", "Mokokchung", "Tuensang", "Wokha", "Zunheboto", "Phek", "Mon", "Peren", "Kiphire", "Longleng", "Noklak"],
  Odisha: [
    "Bhubaneswar", "Cuttack", "Rourkela", "Berhampur", "Sambalpur", "Puri", "Balasore", "Bhadrak",
    "Baripada", "Jharsuguda", "Angul", "Dhenkanal", "Jeypore", "Koraput", "Rayagada", "Bolangir",
    "Bhawanipatna", "Nabarangpur", "Nuapada", "Bargarh", "Sundargarh", "Kendrapara", "Jagatsinghpur", "Jajpur",
    "Phulbani", "Malkangiri", "Nayagarh", "Boudh", "Paralakhemundi", "Sonepur", "Kendujhar", "Deogarh",
  ],
  Punjab: [
    "Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Bathinda", "Mohali", "Hoshiarpur", "Batala",
    "Moga", "Malerkotla", "Khanna", "Muktsar", "Barnala", "Rajpura", "Firozpur", "Kapurthala",
    "Sangrur", "Faridkot", "Gurdaspur", "Fazilka", "Mansa", "Nawanshahr", "Pathankot", "Tarn Taran",
    "Rupnagar", "Ferozepur",
  ],
  Rajasthan: [
    "Jaipur", "Jodhpur", "Kota", "Udaipur", "Bikaner", "Ajmer", "Bhilwara", "Alwar",
    "Sikar", "Bharatpur", "Pali", "Sri Ganganagar", "Kishangarh", "Baran", "Dhaulpur", "Tonk",
    "Beawar", "Hanumangarh", "Churu", "Jhunjhunu", "Nagaur", "Barmer", "Jaisalmer", "Sirohi",
    "Banswara", "Dungarpur", "Rajsamand", "Chittorgarh", "Bundi", "Jhalawar", "Karauli", "Sawai Madhopur",
    "Dausa", "Pratapgarh",
  ],
  Sikkim: ["Gangtok", "Namchi", "Gyalshing", "Mangan", "Rangpo", "Jorethang", "Soreng", "Pakyong"],
  "Tamil Nadu": [
    "Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem", "Tirunelveli", "Erode", "Vellore",
    "Thoothukudi", "Puducherry", "Trichy", "Dindigul", "Thanjavur", "Ranipet", "Sivakasi", "Karur",
    "Namakkal", "Cuddalore", "Kanchipuram", "Nagercoil", "Tiruppur", "Hosur", "Nagapattinam", "Kumbakonam",
    "Pudukkottai", "Ramanathapuram", "Sivaganga", "Villupuram", "Virudhunagar", "Theni", "Krishnagiri", "Ariyalur",
    "Perambalur", "Tiruvannamalai", "Dharmapuri", "Ooty", "Kanyakumari", "Tenkasi", "Tirupathur", "Chengalpattu",
    "Mayiladuthurai", "Kallakurichi",
  ],
  Telangana: [
    "Hyderabad", "Warangal", "Nizamabad", "Karimnagar", "Khammam", "Secunderabad", "Ramagundam", "Mahbubnagar",
    "Nalgonda", "Adilabad", "Siddipet", "Suryapet", "Miryalaguda", "Jagtial", "Mancherial", "Kamareddy",
    "Sangareddy", "Medak", "Nagarkurnool", "Wanaparthy", "Vikarabad", "Bhadradri Kothagudem", "Jangaon",
    "Jayashankar Bhupalpally", "Jogulamba Gadwal", "Kumuram Bheem Asifabad", "Mahabubabad", "Mulugu",
    "Narayanpet", "Peddapalli", "Rajanna Sircilla", "Yadadri Bhuvanagiri",
  ],
  Tripura: ["Agartala", "Udaipur", "Dharmanagar", "Kailashahar", "Belonia", "Khowai", "Ambassa", "Sabroom", "Sonamura", "Kamalpur", "Amarpur", "Teliamura"],
  "Uttar Pradesh": [
    "Lucknow", "Kanpur", "Ghaziabad", "Agra", "Varanasi", "Meerut", "Prayagraj", "Bareilly",
    "Aligarh", "Moradabad", "Noida", "Gorakhpur", "Saharanpur", "Firozabad", "Jhansi", "Muzaffarnagar",
    "Mathura", "Rampur", "Shahjahanpur", "Farrukhabad", "Ayodhya", "Sultanpur", "Basti", "Sitapur",
    "Etawah", "Mirzapur", "Bulandshahr", "Rae Bareli", "Hardoi", "Unnao", "Fatehpur", "Pratapgarh",
    "Jaunpur", "Ghazipur", "Azamgarh", "Mau", "Ballia", "Deoria", "Kushinagar", "Maharajganj",
    "Siddharthnagar", "Balrampur", "Gonda", "Bahraich", "Shrawasti", "Lakhimpur Kheri", "Pilibhit", "Bijnor",
    "Amroha", "Sambhal", "Budaun", "Etah", "Kasganj", "Mainpuri", "Hathras", "Kanpur Dehat",
    "Auraiya", "Jalaun", "Hamirpur", "Mahoba", "Banda", "Chitrakoot", "Kaushambi", "Bhadohi",
    "Chandauli", "Sonbhadra", "Amethi", "Baghpat", "Shamli", "Barabanki",
  ],
  Uttarakhand: [
    "Dehradun", "Haridwar", "Roorkee", "Haldwani", "Rudrapur", "Rishikesh", "Kashipur", "Nainital",
    "Almora", "Pithoragarh", "Pauri", "Tehri", "Uttarkashi", "Chamoli", "Bageshwar", "Champawat",
    "Udham Singh Nagar",
  ],
  "West Bengal": [
    "Kolkata", "Howrah", "Durgapur", "Asansol", "Siliguri", "Bardhaman", "Malda", "Kharagpur",
    "Haldia", "Raiganj", "Krishnanagar", "Baharampur", "Jalpaiguri", "Cooch Behar", "Alipurduar", "Darjeeling",
    "Kalimpong", "Purulia", "Bankura", "Suri", "Nadia", "Chinsurah", "Medinipur", "Tamluk",
    "Barasat", "Alipore", "Jhargram", "Basirhat",
  ],
  "Andaman and Nicobar Islands": ["Port Blair", "Diglipur", "Rangat", "Mayabunder", "Car Nicobar"],
  Chandigarh: ["Chandigarh"],
  "Dadra and Nagar Haveli and Daman and Diu": ["Daman", "Diu", "Silvassa"],
  Delhi: ["New Delhi", "Delhi", "Dwarka", "Rohini", "Karol Bagh", "Saket", "Pitampura", "Janakpuri", "Lajpat Nagar", "Connaught Place"],
  "Jammu and Kashmir": [
    "Srinagar", "Jammu", "Anantnag", "Baramulla", "Sopore", "Kathua", "Udhampur", "Pulwama",
    "Kupwara", "Rajouri", "Poonch", "Budgam", "Bandipora", "Ganderbal", "Shopian", "Kulgam",
    "Doda", "Kishtwar", "Ramban", "Samba",
  ],
  Ladakh: ["Leh", "Kargil"],
  Lakshadweep: ["Kavaratti", "Agatti", "Amini", "Andrott", "Minicoy"],
  Puducherry: ["Puducherry", "Karaikal", "Yanam", "Mahe"],
};

export const INDIA_STATES = Object.keys(INDIA_STATES_AND_CITIES).sort();
